config/routes.rb
ElFinderApp::Application.routes.draw do

  match 'connector' => 'elfinder#connector', via: [:get, :post]
  root 'elfinder#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/elfinder_controller.rb
require 'el_finder/action'
# require 'el_finder/volume'

class ElfinderController < ApplicationController
  include ElFinder::Action

  layout false

  skip_before_filter :verify_authenticity_token, :only => [:connector]

  def index
  end

  el_finder(:connector) do
    {
      volumes: [
        ElFinder::Volume.new(id: 'v1', name: 'Volume 1', root: File.join(Rails.public_path, 'system', 'elfinder1'), url: '/system/elfinder1'),
        ElFinder::Volume.new(id: 'v2', name: 'Volume 2', root: File.join(Rails.public_path, 'system', 'elfinder2'), url: '/system/elfinder2')
      ],
      perms: {
         /^(Welcome|README)$/ => {:read => true, :write => false, :rm => false},
         '.' => {:read => true, :write => false, :rm => false}, # '.' is the proper way to specify the home/root directory.
         /^test$/ => {:read => true, :write => true, :rm => false},
         'logo.png' => {:read => true},
         /\.png$/ => {:read => false} # This will cause 'logo.png' to be unreadable.
                                      # Permissions err on the safe side. Once false, always false.
      },
      extractors: {
        'application/zip' => ['unzip', '-qq', '-o'], # Each argument will be shellescaped (also true for archivers)
        'application/x-gzip' => ['tar', '-xzf'],
      },
      archivers: {
        'application/zip' => ['.zip', 'zip', '-qr9'], # Note first argument is archive extension
        'application/x-gzip' => ['.tgz', 'tar', '-czf'],
      }
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elfinder_helper.rb
module ElfinderHelper
end

app/views/elfinder/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>elFinder 2.0</title>

    <!-- jQuery and jQuery UI (REQUIRED) -->
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/smoothness/jquery-ui.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js"></script>

    <!-- elFinder CSS (REQUIRED) -->
    <link rel="stylesheet" type="text/css" href="elfinder/css/elfinder.min.css">
    <link rel="stylesheet" type="text/css" href="elfinder/css/theme.css">

    <!-- elFinder JS (REQUIRED) -->
    <script src="elfinder/js/elfinder.min.js"></script>

    <!-- elFinder translation (OPTIONAL) -->
    <script src="elfinder/js/i18n/elfinder.ru.js"></script>

    <!-- elFinder initialization (REQUIRED) -->
    <script type="text/javascript" charset="utf-8">
      // Documentation for client options:
      // https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
      $(document).ready(function() {
        $('#elfinder').elfinder({
          url : '<%= connector_path %>'  // connector URL (REQUIRED)
          // , lang: 'ru'                    // language (OPTIONAL)
        });
      });
    </script>
  </head>
  <body>

    <!-- Element where elFinder will be created (REQUIRED) -->
    <div id="elfinder"></div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElFinderApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>